print("Ejemplo de listas")
arcoiris=["verde", "azul", "rojo"]
print(arcoiris)
longitud=len(arcoiris)
print("Numero de elementos que contiene la lista arcoiris:",longitud)
print(f"Numero de elementos que contiene la lista arcoiris v2: {longitud}")
print("Accediendo a un elemento:",arcoiris[1])
print(f"Elemento en la posicion 0 es: {arcoiris[0]}")
print("El tercer color del arcoiris es:",arcoiris[2])
print("Agregar un elemento a la lista ")
arcoiris.append("naranja")
print(arcoiris)
print("Listar los elementos de la lista ciclo for")
for alvarez in arcoiris:
    print(alvarez)
